name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Clean Environment
      run: |
        sudo rm -rf ~/.npm ~/.cache ~/.cargo
        sudo rm -rf /home/runner/work/_actions

    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Download Upload Artifact Manually
      run: |
        git clone https://github.com/actions/upload-artifact.git
        cd upload-artifact
        git checkout v3.2.0

    - name: Set up Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential ccache curl git unzip wget \
          python3 python3-pip rsync libncurses5-dev zlib1g-dev gawk \
          gettext openssl libssl-dev xsltproc time \
          python3-distutils python3-setuptools
        sudo timedatectl set-timezone "$TZ"

    - name: Clone OpenWrt Source
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load Custom Feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update Feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install Feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download Packages
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
        DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
        echo "DEVICE_NAME=_${DEVICE_NAME}" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Upload Bin Directory
      run: |
        cd upload-artifact
        node dist/index.js --name OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }} --path openwrt/bin

    - name: Organize Files
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
